REQUEST = "car+dealerships+in+Adelaide/"
BASIC_URL = "https://www.google.com/maps/search/"
URL = BASIC_URL + REQUEST
PARALLEL_BROWSER_INSTANCES_COUNT = 1
LOOP_SCRAPING_INTERVAL_TIME = 3
WAIT_ELEMENT_To_APPEAR = 10

# PARENT SCROLLABLE
PARENT_SCROLLABLE_SELECTOR = ".m6QErb.DxyBCb.kA9KIf.dS8AEf.XiKgde.ecceSd"
NUMBER_ELEMENT_PER_SCROLL = 5
# PLACES IN LIST
PLACE_CONTAINER_SELECTOR = ".Nv2PK.THOPZb.CpccDe"
