import re

REQUEST = "grossistes pharmaceutique algerie"
PROJECT_NAME = re.sub(" ", "_", REQUEST)
BASIC_URL = "https://www.google.com/maps/search/"
URL = BASIC_URL + REQUEST
PARALLEL_BROWSER_INSTANCES_COUNT = 1
LOOP_SCRAPING_INTERVAL_TIME = 0.2
WAIT_ELEMENT_To_APPEAR = 20
WAIT_ELEMENT_APPEAR = 15
SCRAPE_PLACES_INTERVAL = 3
NO_ELEMENT_TO_SCRAPE_MESSAGE = "No element is found to scrape"

# DEFINE TIMES CONSTANTS
TIME_1 = 1
TIME_2 = 2
TIME_3 = 3
TIME_4 = 4
TIME_5 = 5
TIME_8 = 8
TIME_10 = 10
TIME_12 = 12
TIME_15 = 15
# PARENT SCROLLABLE
PARENT_SCROLLABLE_SELECTOR = ".m6QErb.DxyBCb.kA9KIf.dS8AEf.XiKgde.ecceSd>*"
NUMBER_ELEMENT_PER_SCROLL = 5

# PLACES IN LIST
PLACE_CONTAINER_SELECTOR = ".Nv2PK.THOPZb"
"""PLACE_CONTAINER_SELECTOR_2 = ".Nv2PK.tH5CWc.THOPZb"
PLACE_CONTAINER_SELECTOR_3 = ".Nv2PK.Q2HXcd.THOPZb"""

PLACE_DETAILS_SELECTOR = ".Io6YTe.kR99db.fdkmkc"
PLACE_DETAILS_CONTAINER_SELECTOR = ".e07Vkf.kA9KIf"

# OTHER REGEX
WEBSITE_PATTERN = r"^(https?:\/\/)?(www\.)?[a-zA-Z0-9-]+(\.[a-zA-Z]{2,})+$"
PHONE_NUMBER_PATTERN = r"^\+?([0-9]{1,4}\s?)+$"

# Database constants
MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = "0901"
MYSQL_DATABASE = "googlemaps"
